name: Pytest and PEP8

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10.7
      uses: actions/setup-python@v3
      with:
        python-version: 3.10.7
        architecture: "x64"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are PEP8 violation
        flake8 --select=E . 
    - name: Test with pytest
      run: |
        pip install pytest
        pytest qBnB_test/*